services:
  app:
    build: .
    container_name: generallm  # Set the container name here
    ports:
      - "8000:8000"
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - MODEL_NAME=${MODEL_NAME}
    volumes:
      - ./app:/app
