# fly.toml app configuration file generated for generallm on 2024-10-13T17:19:07-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'generallm'
primary_region = 'den'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '3gb'
  cpu_kind = 'shared'
  cpus = 2
